const {test,expect}=require('@playwright/test');
const {PDFDocument,StandardFonts}=require('pdf-lib');
const fs=require('node:fs/promises');
async function fixture(){const doc=await PDFDocument.create();const font=await doc.embedFont(StandardFonts.Helvetica);for(let i=0;i<3;i++){const p=doc.addPage([595,842]);p.drawText('SECRET OFFICE '+(i+1),{x:60,y:60,size:16,font});}return Buffer.from(await doc.save());}
async function open(page,id){await page.goto('/?tool='+id);await expect(page.locator('#modal')).toHaveClass(/active/);}
async function upload(page,id){await page.locator(id).setInputFiles({name:'office.pdf',mimeType:'application/pdf',buffer:await fixture()});}
async function result(page,button){await expect(page.locator(button)).toBeEnabled();await page.locator(button).click();await expect(page.locator('.result-panel')).toHaveClass(/active/);const pending=page.waitForEvent('download');await page.locator('#resultDownloadBtn').click();const download=await pending;return fs.readFile(await download.path());}
test('dashboard, every registered tool and no runtime errors',async({page})=>{const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');await expect(page.locator('#homeContent .tool-card')).toHaveCount(17);const cards=page.locator('#homeContent .tool-card');for(let i=0;i<17;i++){await cards.nth(i).click();await expect(page.locator('#modalBody [data-role=process]')).toHaveCount(1);await page.locator('#modalClose').click();}expect(errors).toEqual([]);});
test('merge downloads six pages and malicious filename stays text',async({page})=>{await open(page,'merge');const buffer=await fixture();await page.locator('#mIn').setInputFiles([{name:'<img src=x onerror=alert(1)>.pdf',mimeType:'application/pdf',buffer},{name:'second.pdf',mimeType:'application/pdf',buffer}]);await expect(page.locator('#mList img')).toHaveCount(0);const doc=await PDFDocument.load(await result(page,'#mBtn'));expect(doc.getPageCount()).toBe(6);});
test('split range and compression preserve physical dimensions',async({page})=>{await open(page,'split');await upload(page,'#sIn');await expect(page.locator('#sBtn')).toBeEnabled();await page.locator('#sFrom').fill('2');await page.locator('#sTo').fill('3');expect((await PDFDocument.load(await result(page,'#sBtn'))).getPageCount()).toBe(2);await page.locator('#modalClose').click();await open(page,'compress');await upload(page,'#cIn');const doc=await PDFDocument.load(await result(page,'#cBtn'));expect(doc.getPageCount()).toBe(3);expect(doc.getPage(0).getSize()).toEqual({width:595,height:842});});
test('redaction removes extractable original text',async({page})=>{await open(page,'redact');await upload(page,'#rdIn');await expect(page.locator('.redact-row')).toHaveCount(1);const bytes=await result(page,'#rdBtn');const doc=await PDFDocument.load(bytes);expect(doc.getPageCount()).toBe(3);const extracted=await page.evaluate(async bytes=>{const pdf=await window.pdfjsLib.getDocument({data:new Uint8Array(bytes),isEvalSupported:false}).promise;let text='';for(let i=1;i<=pdf.numPages;i++)text+=(await(await pdf.getPage(i)).getTextContent()).items.map(x=>x.str).join('');await pdf.destroy();return text;},[...bytes]);expect(extracted).toBe('');});
test('invalid file and enormous page range are rejected',async({page})=>{await open(page,'extract');await page.locator('#eIn').setInputFiles({name:'wrong.pdf',mimeType:'application/pdf',buffer:Buffer.from('not a pdf')});await expect(page.locator('#eBtn')).toBeDisabled();await upload(page,'#eIn');await expect(page.locator('#eBtn')).toBeEnabled();await page.locator('#ePages').fill('1-9999999999999');await page.locator('#eBtn').click();await expect(page.locator('#toastContainer')).toContainText('Choose pages between');});
test('office name persists as text and storage failures do not break tools',async({page,context})=>{await page.goto('/');await page.locator('#officeName').fill('<img src=x onerror=alert(1)>');await page.locator('#officeForm button').click();await page.reload();await expect(page.locator('#officeHeading')).toContainText('<img');await expect(page.locator('#officeHeading img')).toHaveCount(0);await context.addInitScript(()=>{Storage.prototype.getItem=()=>{throw new Error('blocked')};Storage.prototype.setItem=()=>{throw new Error('blocked')};});await page.reload();await expect(page.locator('#homeContent .tool-card')).toHaveCount(17);});
test('HTML and CV inputs cannot create executable elements',async({page})=>{await page.goto('/');await page.locator('[data-view=cv]').click();await page.locator('#cvEmail').fill('<img src=x onerror=alert(1)>');await expect(page.locator('#rpContact img')).toHaveCount(0);await open(page,'html2pdf');await page.locator('#hC').fill('<p>Safe text</p><img src="https://example.com/leak"><script>alert(1)</script>');let leaked=false;page.on('request',r=>{if(r.url().includes('example.com/leak'))leaked=true;});const download=page.waitForEvent('download');await page.locator('#hBtn').click();await download;expect(leaked).toBe(false);});
test('mobile layout and dialog focus',async({page})=>{await page.setViewportSize({width:390,height:844});await page.goto('/');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.locator('#homeContent .tool-card').first().click();await expect(page.locator('#modalClose')).toBeFocused();await page.keyboard.press('Escape');await expect(page.locator('#modal')).not.toHaveClass(/active/);});
test('OCR returns recognized English text from a synthetic PDF',async({page})=>{test.setTimeout(180000);await open(page,'ocr');await upload(page,'#ocrIn');await expect(page.locator('#ocrBtn')).toBeEnabled();await page.locator('#ocrBtn').click();await expect(page.locator('.result-panel')).toHaveClass(/active/,{timeout:150000});const pending=page.waitForEvent('download');await page.locator('#resultDownloadBtn').click();const bytes=await fs.readFile(await(await pending).path());expect(bytes.toString()).toContain('SECRET OFFICE');});
test('cached core tools work offline and missing assets are not HTML',async({page,context})=>{await page.goto('/');await page.evaluate(()=>navigator.serviceWorker.ready);await page.reload();await expect(page.locator('#homeContent .tool-card')).toHaveCount(17);const missing=await page.request.get('/vendor/missing.js');expect(missing.status()).toBe(404);await context.setOffline(true);await page.reload();await expect(page.locator('#homeContent .tool-card')).toHaveCount(17);await context.setOffline(false);});
test('organizing a long PDF preserves pages beyond thumbnail limit',async({page})=>{await open(page,'organize');const doc=await PDFDocument.create();for(let i=0;i<51;i++)doc.addPage([200+i,300]);await page.locator('#oIn').setInputFiles({name:'long.pdf',mimeType:'application/pdf',buffer:Buffer.from(await doc.save())});await expect(page.getByRole('button',{name:'Move page later 1',exact:true})).toBeVisible();await page.getByRole('button',{name:'Move page later 1',exact:true}).click();const output=await PDFDocument.load(await result(page,'#oBtn'));expect(output.getPageCount()).toBe(51);expect(output.getPage(0).getWidth()).toBe(201);expect(output.getPage(50).getWidth()).toBe(250);});
