const fs=require('node:fs');
const origin='https://www.pdf.salaroutsourcing.com';
const pages=[
 ['merge-pdf','Merge PDF files privately','Combine contracts, invoices or reports into one PDF without sending document contents to a server.','merge',[
 ['How to merge PDFs','Choose two or more unencrypted PDFs. Drag the files into the required order, choose the output page size if needed, then select Merge PDFs. Download the result and check the page count and order before sharing.'],
 ['What happens to my files?','Merging runs in this browser using PDF-lib. The application does not upload PDF contents. Original files are unchanged; the output is a separate download.'],
 ['Limits and document features','Each file can be up to 100 MB and each selection up to 200 MB. Complex PDFs may exceed available memory. Check forms, links, bookmarks and signatures after merging; this tool does not promise preservation of all interactive features.'],
 ['Office example','Put a cover letter first, a proposal second and supporting invoices last. Use a consistent filename such as project-proposal.pdf after reviewing the download.']]],
 ['split-pdf','Split and extract PDF pages','Save a continuous page range from a PDF, or use Extract Pages for specific pages.','split',[
 ['How to split a PDF','Choose an unencrypted PDF. Enter the first and last page of the range, using the displayed document page numbers. Select Split PDF, then download and open the result.'],
 ['Can I select pages that are not next to each other?','Use Extract Pages on the dashboard. Enter numbers and ranges such as 1,3,5-7. Only pages within the document are accepted.'],
 ['Privacy and limits','The document is processed in this browser. PDF contents are not uploaded by the app. The file limit is 100 MB; complex files may need more memory than the browser can provide.'],
 ['Office example','Extract the relevant pages from a supplier catalogue before sending a purchase request. Check that the result contains only the intended pages.']]],
 ['compress-pdf','Compress scanned PDFs','Create an image-only PDF with adjustable image quality and resolution. Compression is not lossless and may increase file size.','compress',[
 ['How compression works','Each page is rendered as an image and embedded in a new PDF. Choose an image quality and resolution, run Compress PDF, and compare the reported output size with the original. Physical page dimensions are preserved.'],
 ['What will I lose?','Selectable text, forms, links and original document structure are lost. Keep your original when these features matter. For a text-heavy PDF, the original may already be smaller than the image-only output.'],
 ['What should I check?','Open the output and inspect small text, stamps, diagrams and signatures at normal reading size. If the result is larger or less readable, keep the original or try a different setting.'],
 ['Office example','Try compression on scanned receipts for an email attachment. Avoid this workflow for accessible documents or forms that recipients need to fill in.']]],
 ['redact-pdf','Redact PDF regions','Cover selected regions and rebuild every page as an image so original text cannot be recovered from the output text layer.','redact',[
 ['How to redact a PDF','Choose a PDF. Add a rectangle for each region to remove using a page number, X and Y coordinates, width and height. Coordinates are in PDF points from the bottom-left of the page. Run Apply Redactions and review every output page before sharing.'],
 ['Why black boxes alone are not enough','Drawing a black rectangle over an existing PDF can leave the text underneath extractable. This tool instead renders pages, paints the selected regions black and creates a new image-only PDF. It does not copy original page content streams, attachments or metadata.'],
 ['What changes in the output?','All pages become images. Searchable text, links, forms and accessibility structure are lost. The file can become larger. Cropping is different: it hides margins and is not a substitute for redaction.'],
 ['Review is essential','The tool cannot identify confidential information for you. Confirm the rectangle fully covers the intended content, inspect all pages, and check that sensitive information does not appear elsewhere.']]],
 ['ocr-pdf','Extract English text from scanned PDFs','Use browser-based OCR to download recognized English text as a TXT file.','ocr',[
 ['How to extract text','Choose a scanned, unencrypted PDF and select Extract text. The English OCR model downloads when needed. Pages are processed in order and the result is available as a text download with page separators.'],
 ['Does OCR upload the document?','The application processes pages on your device. It downloads OCR software and a language model, but does not send PDF contents to the model provider. The provider can receive normal connection information such as your IP address.'],
 ['Accuracy and format','This tool currently supports English text extraction. OCR can misread names, amounts, dates and handwriting. Review the text against the original. It does not create a layout-preserving Word file or a searchable PDF.'],
 ['Office example','Extract text from a scanned letter, then review and copy the relevant passage into an internal note. Do not rely on unverified OCR text for important amounts or identifiers.']]],
 ['office-pdf-workspace','A PDF workspace for your office','Give everyday paperwork a familiar home with an office name, favorite tools and browser installation.','',[
 ['Make it feel like your office','Enter your office name on the dashboard and choose Make it mine. Your name appears above the tools. Favorite frequently used tools using the heart button on each card.'],
 ['Share a setup, not documents','The setup link contains the office name in its URL fragment. Anyone with the link can see that name. Each recipient chooses whether to save it in their own browser. It does not grant access to files, accounts or shared storage.'],
 ['Install for quick access','Use Install app on the dashboard or your browser’s Add to Home Screen / Install menu. The installed app is named PDF Toolkit. Your office branding appears inside the app. Core assets are cached after a successful visit; OCR needs its language model.'],
 ['Is this a staff account system?','No. This release stores the office name and tool preferences in the current browser. It does not provide sign-in, staff invitations, administrator roles, cross-device synchronization or a shared document vault. Clearing site data removes these preferences.']]],
 ['privacy','Privacy and tool limitations','Understand document processing, local preferences, network requests and limitations before using PDF Toolkit.','',[
 ['Who maintains the project?','PDF Toolkit is maintained through the Salaroutsourcing/pdf repository on GitHub. Use the repository issue tracker to report reproducible bugs without including confidential documents.'],
 ['Document handling','The current application processes PDF and image contents in your browser. It does not include a document upload API or server-side document storage. Downloaded outputs remain on your device. Closing the tool releases its document references; this is not a guarantee of secure memory erasure.'],
 ['Preferences and network traffic','Office names, favorite tool IDs, recent tool IDs and theme choices are stored in local browser storage. App assets may be cached by a service worker. Google Fonts, hosting and OCR model requests expose ordinary connection metadata. The app does not store PDF contents in local storage or the service worker cache.'],
 ['Important limits','PDF files must be unencrypted and no larger than 100 MB each. Compression and redaction produce image-only output. Signature placement is not certificate signing. OCR is English-only and fallible. No certification, security audit or compliance guarantee is claimed.']]]
];
const escape=s=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
for(const [slug,title,desc,tool,sections] of pages){
 const url=`${origin}/${slug}/`;
 const schema={'@context':'https://schema.org','@type':'WebPage',name:title,description:desc,url,isPartOf:{'@type':'WebSite',name:'PDF Toolkit',url:origin+'/'}};
 const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${title} | PDF Toolkit</title><meta name="description" content="${escape(desc)}"><link rel="canonical" href="${url}"><meta property="og:title" content="${escape(title)}"><meta property="og:description" content="${escape(desc)}"><meta property="og:url" content="${url}"><meta property="og:type" content="website"><meta name="robots" content="index,follow,max-snippet:-1,max-image-preview:large"><script type="application/ld+json">${JSON.stringify(schema)}</script><style>body{margin:0;background:#f8fafc;color:#172239;font:17px/1.8 system-ui,sans-serif}main{max-width:800px;margin:0 auto;padding:32px 24px 70px}nav{display:flex;gap:24px;flex-wrap:wrap}a{color:#1d4ed8}h1{font-size:clamp(32px,5vw,48px);line-height:1.15;letter-spacing:-.04em;margin:48px 0 20px}h2{font-size:23px;line-height:1.35;margin:36px 0 12px}.cta{display:inline-block;border-radius:10px;padding:12px 22px;background:#1d4ed8;color:white;text-decoration:none;margin:18px 0}footer{border-top:1px solid #cbd5e1;margin-top:42px;padding-top:20px;font-size:14px}:focus-visible{outline:3px solid #1d4ed8;outline-offset:4px}</style></head><body><main><nav><a href="/">PDF Toolkit</a><a href="/office-pdf-workspace/">For offices</a><a href="/privacy/">Privacy</a></nav><h1>${title}</h1><p>${desc}</p><a class="cta" href="/${tool?'?tool='+tool:''}">${tool?'Open tool':'Open your workspace'}</a>${sections.map(([h,p])=>`<section><h2>${h}</h2><p>${p}</p></section>`).join('')}<footer><p>Maintained by <a href="https://github.com/Salaroutsourcing/pdf">Salaroutsourcing/pdf</a>. <a href="https://github.com/Salaroutsourcing/pdf/issues">Report a bug</a>. Documentation updated September 23, 2026.</p><nav>${pages.filter(p=>p[0]!==slug).map(p=>`<a href="/${p[0]}/">${p[1]}</a>`).join('')}</nav></footer></main></body></html>`;
 fs.mkdirSync(slug,{recursive:true});fs.writeFileSync(slug+'/index.html',html);
}
fs.writeFileSync('sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${['',...pages.map(p=>p[0]+'/')].map(p=>`<url><loc>${origin}/${p}</loc></url>`).join('\n')}\n</urlset>\n`);
let index=fs.readFileSync('index.html','utf8');
const guide=`<!-- public-guide:start --><section class="public-guide"><h2>Private PDF tools for everyday office work</h2><p>PDF Toolkit processes documents in your browser. Merge, split, convert, sign and prepare PDFs without the app uploading their contents. Learn the steps and limitations before working with important documents.</p><ul>${pages.map(p=>`<li><a href="/${p[0]}/">${p[1]}</a> — ${p[2]}</li>`).join('')}</ul><p><a href="https://github.com/Salaroutsourcing/pdf">View source</a> · <a href="https://github.com/Salaroutsourcing/pdf/issues">Report a bug</a></p></section><!-- public-guide:end -->`;
index=index.replace(/[ \t]*<!-- public-guide:start -->[\s\S]*?<!-- public-guide:end -->[ \t]*\n?/,'');
index=index.replace('</main>',guide+'\n</main>');fs.writeFileSync('index.html',index);
